<?php

namespace UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package UserBundle\Entity
 */
class UserRepository extends EntityRepository
{
}
